name: "build"

on:
  push:
    branches:
      - main

env:
  PROJECT_PATH: 'src'

jobs:
  build:
    name: 'build-check'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.x.x' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore packages
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build project
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release